### ISSUE TITLE
default content type header

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/web-ledger-client#11]
https://github.com/digitalbazaar/web-ledger-client/blob/1d6f7ed9250d13924034de9a2789801e4871de32/lib/methods/veres-one-client.js#L11-L14

- `lib/methods/veres-one-client.js` is defining a comma separated list of media-types for `Content-type`.  I think it should only be one.  See https://tools.ietf.org/html/rfc7231#section-3.1.1.5
- Why `Content-type` vs `Content-Type`?  I imagine axios will merge all cases into one header, but to avoid some ordering issue, we likely should standardize on either the spec cap spellings or all lowercase.  Probably the spec caps version of `Content-Type`?

**Comment by dmitrizagidulin** [comment]
@davidlehn good call on both points. Will fix.

**Comment by dmitrizagidulin** [comment]
(Both issues should be fixed in PR #10.)

**Comment by dmitrizagidulin** [comment]
Addressed in PR #10, closing.
