### ISSUE TITLE
Enable Travis CI for this repo

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/web-ledger-client#9]
Can somebody with Travis CI permission for the DigitalBazaar org enable tests for this repo?

**Comment by davidlehn** [comment]
Done: https://travis-ci.org/digitalbazaar/web-ledger-client

**Comment by davidlehn** [comment]
And sorry about rdf-cannonize!  Will need that c++ compiler upgrade code.  I'll try to find time to get that native split code out soon so tests can just use js w/o silly hacks.
